Fix DiffEqDiffTools package redirect
JuliaRegistries/General pull request #11578
Opened 2020-03-25 23:43 UTC by ChrisRackauckas

JuliaDiffEq/DiffEqDiffTools -> JuliaDiff/FiniteDiff.jl, and now it seems the link forwarding broke, so this should fix it again.

2020-03-25 23:43 UTC, ChrisRackauckas commented
@DilumAluthge or @KristofferC can we get a quick review on this? Should fix https://github.com/TuringLang/MCMCChains.jl/pull/193#issuecomment-604143859

2020-03-25 23:46 UTC, DilumAluthge requested changes
Unfortunately this pull request does two things:
1. Change the GitHub organization
2. Change the name of the package

These two tasks must be done separately.

2020-03-25 23:47 UTC, ChrisRackauckas commented
So two PRs? That makes a difference?

2020-03-25 23:47 UTC, DilumAluthge commented
In particular, we do not allow people to rename packages in this way.

A package rename is done by generating a new UUID. The README has full details. I can also assist with this.

The changing of the organization is totally fine. You can make a separate PR that does this.

Let me know how I can help.

2020-03-25 23:48 UTC, DilumAluthge commented
> So two PRs? That makes a difference?

So, unfortunately, renaming the package is not so easy. You essentially create a new package, with a new UUID.

2020-03-25 23:48 UTC, DilumAluthge commented
Otherwise, you break everyone's code that uses the old name of the package.

2020-03-25 23:48 UTC, ChrisRackauckas commented
The package was renamed months ago though.

2020-03-25 23:48 UTC, DilumAluthge commented
> How do I rename an existing registered package?

> Technically, you can't rename a package once registered, as this would break existing users. But you can re-register the package again under a new name with a new UUID. Which has basically the same effect.

>     Follow the instructions above for renaminging a package: rename on GitHub, rename files etc.
>     Generate a new UUID for the Project.toml
>     Increment the version in the Project.toml as a breaking change.
>     Register it as if it were a new package
    Comment on the PR, that this is a rename.
    It will have to go though the normal criteria for registring a new package.
        In particular, even if you get it merged manually, it will need to wait 3 days from the PR being opened.
        This gives others and yourself the chance to point out any naming issues.

You also should let your users know about the rename, e.g. by placing a note in the README, or opening PRs/issues on downstream packages to change over.

2020-03-25 23:49 UTC, DilumAluthge commented
> The package was renamed months ago though.

That shouldn't have been done.

2020-03-25 23:49 UTC, DilumAluthge commented
Did you rename the package without making any changes to the registry?

2020-03-25 23:50 UTC, ChrisRackauckas commented
Yeah. IIRC I just followed what @StefanKarpinski said the procedure was.

2020-03-25 23:50 UTC, ChrisRackauckas commented
Everyone's code was working fine, until JuliaDiffEq -> SciML.

2020-03-25 23:50 UTC, DilumAluthge commented
> Yeah. IIRC I just followed what @StefanKarpinski said the procedure was.

Hmmm. So what steps did you take to rename the package?

2020-03-25 23:51 UTC, DilumAluthge commented
> Everyone's code was working fine, until JuliaDiffEq -> SciML.

Yeah.... so it wasn't actually working fine. It was relying on GitHub's secret hidden redirects. They redirect renamed repos, but not renamed orgs.

2020-03-25 23:51 UTC, ChrisRackauckas commented
Oh actually:

https://github.com/JuliaRegistries/General/pull/7516

>Looks good to me.

2020-03-25 23:51 UTC, DilumAluthge commented
Oh you did it right then!

2020-03-25 23:52 UTC, DilumAluthge commented
So you did do the correct thing. So why is this PR needed?

2020-03-25 23:52 UTC, DilumAluthge commented
Ohhhh I get it now.

2020-03-25 23:52 UTC, ChrisRackauckas commented
Alright, so we just fix the URL and it should work again? If this is an actual fix, I hope we can just get it out sooner rather than later, since I'd rather not just keep someone's CI broken to discuss how we should do this if it works.

2020-03-25 23:53 UTC, DilumAluthge commented
Wait, so I am a little confused as to what is broken right now?

2020-03-25 23:53 UTC, ChrisRackauckas commented
the redirect.

2020-03-25 23:56 UTC, DilumAluthge commented
Okay, it's good that this happened because it exposes a serious flaw in how we currently rename packages.

For now, let's merge this and see if it doesn't break anything.

I'll open an issue to discuss the issue in how we rename packages.

2020-03-25 23:56 UTC, merged

2020-03-26 00:02 UTC, DilumAluthge commented
@ChrisRackauckas Can you check if this fixed the issue, and let me know?

2020-03-26 00:08 UTC, ChrisRackauckas commented
```
(v1.0) pkg> up
  Updating registry at `C:\Users\accou\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.0\Project.toml`
 [no changes]
  Updating `C:\Users\accou\.julia\environments\v1.0\Manifest.toml`
 [no changes]

(v1.0) pkg>

(v1.0) pkg> add DiffEqDiffTools
 Resolving package versions...
  Updating `C:\Users\accou\.julia\environments\v1.0\Project.toml`
  [01453d9d] + DiffEqDiffTools v1.6.0
  Updating `C:\Users\accou\.julia\environments\v1.0\Manifest.toml`
 [no changes]
```

looks fine

2020-03-26 00:22 UTC, DilumAluthge commented
@ChrisRackauckas Perfect!

Keep your ear to the ground, and if you hear of this PR breaking anything, can you let me know, and I can try to cook up another solution?

2020-03-26 00:25 UTC, ChrisRackauckas commented
Indeed, though I may move my ear.