Yank ArrayInterfaceStaticArraysCore 0.1.2
JuliaRegistries/General pull request #70213
Opened 2022-10-14 14:09 UTC by chriselrod

It requires a recent ArrayInterfaceCore, but did not update the compat.

2022-10-14 14:12 UTC, DilumAluthge requested changes

2022-10-14 14:12 UTC, DilumAluthge commented on A/ArrayInterfaceStaticArraysCore/Versions.toml
> +yank=true
```suggestion
yanked = true
```

2022-10-14 14:38 UTC, DilumAluthge approved these changes

2022-10-14 14:45 UTC, merged

2022-10-14 17:26 UTC, jishnub commented
What's the policy here: would it be possible to update the compat limit listed in the registry at the risk of incompatibility between the registry and the repo? Or does one yank versions with incorrect compat limits?

2022-10-15 00:57 UTC, chriselrod commented
Registered packages are supposed to be immutable, so I just registered one with a fix and yanked the old.